-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES TABLE (Public / No Auth)
-- Stores user data directly without linking to auth.users
create table public.profiles (
  id text primary key, -- Generated by app (e.g., UUID string)
  name text,
  avatar_url text,
  bio text,
  xp integer default 0,
  chef_level text default 'Beginner',
  badges jsonb default '[]'::jsonb,
  stats jsonb default '{"recipesCooked": 0, "savedRecipes": 0, "sharedRecipes": 0, "daysStreak": 0}'::jsonb,
  dietary_preferences jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Profiles (Public Access)
alter table public.profiles enable row level security;

-- Allow anyone to read profiles
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

-- Allow anyone to create/update profiles (Client provides ID)
create policy "Public profiles are editable by everyone."
  on profiles for all
  using ( true )
  with check ( true );

-- 2. RECIPES TABLE
-- Stores recipes created by users
create table public.recipes (
  id uuid default gen_random_uuid() primary key,
  author_id text references public.profiles(id) not null, -- Links to public.profiles.id
  original_id text, -- ID from local device state
  title text not null,
  description text,
  image_url text,
  category text,
  tags jsonb default '[]'::jsonb,
  time text,
  servings integer,
  calories text,
  ingredients jsonb default '[]'::jsonb, -- Stores array of IngredientSection
  steps jsonb default '[]'::jsonb,       -- Stores array of Step
  is_traditional boolean default false,
  rating numeric default 0,
  reviews_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Recipes (Public Access)
alter table public.recipes enable row level security;

create policy "Recipes are viewable by everyone."
  on recipes for select
  using ( true );

create policy "Recipes are editable by everyone."
  on recipes for all
  using ( true )
  with check ( true );

-- 3. STORAGE SETUP
-- Create a storage bucket for 'recipes' and 'avatars'
insert into storage.buckets (id, name, public)
values ('recipes', 'recipes', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

-- Storage Policies (Public Access)
-- Recipes Bucket
create policy "Recipe images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'recipes' );

create policy "Anyone can upload recipe images."
  on storage.objects for insert
  with check ( bucket_id = 'recipes' );

create policy "Anyone can update recipe images."
  on storage.objects for update
  using ( bucket_id = 'recipes' );

-- Avatars Bucket
create policy "Avatar images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'avatars' );

create policy "Anyone can upload avatars."
  on storage.objects for insert
  with check ( bucket_id = 'avatars' );

create policy "Anyone can update avatars."
  on storage.objects for update
  using ( bucket_id = 'avatars' );

-- 4. TRIGGERS
-- Handle updated_at timestamps
create or replace function handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger on_profiles_updated
  before update on public.profiles
  for each row execute procedure handle_updated_at();

create trigger on_recipes_updated
  before update on public.recipes
  for each row execute procedure handle_updated_at();
